# Telegram bot token
TELEGRAM_BOT_TOKEN: ""

# ID of the channel where the bot will write
TELEGRAM_CHANNEL_ID: ""

# Server in the Matrix where the bot and room are located
# For example "https://matrix.org"
BOT_HOME_SERVER: ""

# Bot name in Matrix
# For example: "@bottest:matrix.org"
MATRIX_BOT_NAME: ""

# Bot password in Matrix
MATRIX_BOT_PASSWORD: ""

# ID of the room where the bot will write in Matrix
# For example: "!sdJpefjnKLoreIOdsS:matrix.org"
MATRIX_ROOM_ID: ""

# IP on which the bot will run
# For example 127.0.0.1
HOST_IP: "127.0.0.1"

# Port for sending messages from Telegram to Matrix
TELEGRAM_TO_MATRIX: 5001

# Port for sending messages from Matrix to Telegram
MATRIX_TO_TELEGRAM: 5003
